---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # General Text + YAML Lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key

  # Markdown lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.1
    hooks:
      - id: markdownlint
        args: [--config=.github/markdown_lint.yaml]

  # Rst Lint
  #- repo: https://github.com/myint/rstcheck
  #  rev: v3.3.1
  #  hooks:
  #    - id: rstcheck
