---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.23.0
    hooks:
      - id: yamllint
        args: ['-d {extends: default, rules: {line-length: disable}}']

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: master
    hooks:
      - id: markdownlint
        name: markdownlint
        language: node
        types: [markdown]
        minimum_pre_commit_version: 0.15.0

  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.0
    hooks:
      - id: rst-linter
        description: "rst-linter"
        entry: "rst-linter"
