name: Install

# Global workflow environment variables
env:
    PHYLO_NF_REV: "master"
    EAGER_NF_REV: "7b51863957"
    PHYLO_CONDA_ENV: "plague-phylogeography-0.1.4dev"
    EAGER_CONDA_ENV: "nf-core-eager-2.2.0dev"


#This is a workflow for installation testing.
on:
  # Triggered on Push for any branch
  push:
    branches:
      - '*'
    # On change to workflow, pipeline
    paths:
      - '.github/workflows/install.yaml'
      - 'main.nf'
      - 'environment.yaml'

  # Triggered on PR for all branches, pipeline
  pull_request:
    branches:
      - '*'
  # Also on a published release
  release:
    types: [published]


jobs:

  nextflow:
    runs-on: ubuntu-latest
    steps:

      # 1. Install nextflow
      - name: install nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      # 2. Setup conda
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true

      # 3. Install ktmeaton/plague-phylogeography
      - name: install ktmeaton/plague-phylogeography
        shell: bash -l {0}
        run: |
          nextflow pull ktmeaton/plague-phylogeography
          nextflow pull ktmeaton/plague-phylogeography -r ${PHYLO_NF_REV}
          conda env create -f  ~/.nextflow/assets/ktmeaton/plague-phylogeography/environment.yaml

      # 4. Install nf-core/eager
      - name: install nf-core/eager
        shell: bash -l {0}
        run: |
          nextflow pull nf-core/eager
          nextflow pull nf-core/eager -r ${EAGER_NF_REV}
          conda env create -f ~/.nextflow/assets/nf-core/eager/environment.yml
          conda install -n ${EAGER_CONDA_ENV} -c anaconda graphviz
