name: Install
#This is a workflow for installation testing.
on:
  # Triggered on Push for any branch
  push:
    branches:
      - '*'
    # On change to workflow, pipeline
    paths:
      - '.github/workflows/install.yaml'
      - 'pipeline.nf'
      - 'phylo-env.yaml'

  # Triggered on PR for all branches, pipeline
  pull_request:
    branches:
      - '*'
  # Also on a published release
  release:
    types: [published]


jobs:

  nextflow:
    runs-on: ubuntu-latest
    steps:

      # 1. Install nextflow
      - name: install nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      # 2. Setup conda
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true

      # 4. Install nf-core/eager
      - name: install nf-core/eager
        env:
          NF_REV: "7b51863957"
          CONDA_ENV: "nf-core-eager-2.2.0dev"
        shell: bash -l {0}
        run: |
          nextflow pull nf-core/eager -r ${NF_REV}
          conda env create -f ~/.nextflow/assets/nf-core/eager/environment.yml
          conda install -n ${CONDA_ENV} -c anaconda graphviz

      # 3. Install ktmeaton/plague-phylogeography
      - name: install ktmeaton/plague-phylogeography
        env:
          NF_REV: "master"
          CONDA_ENV: "phylo-env"
        shell: bash -l {0}
        run: |
          nextflow pull ktmeaton/plague-phylogeography -r ${NF_REV}
          conda env create -f  ~/.nextflow/assets/ktmeaton/plague-phylogeography/phylo-env.yaml
