name: Linting
#This is a workflow for linting

on:
  # Triggered on Push for all branches
  push:
    branches:
      - '*'
    # On change to workflow, README, CHANGELOG
    paths:
      - '.github/workflows/linting.yaml*'
      - '.github/markdown_lint.yaml'
      - 'README.md'
      - 'CHANGELOG.md'
  # Triggered on PR for all branches, any file
  pull_request:
    branches:
      - '*'

jobs:

  # Markdown template from nf-core eager to trial
  markdown_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Run Markdownlint
        run: |
          markdownlint CHANGELOG.md -c ${GITHUB_WORKSPACE}/.github/markdown_lint.yaml
          markdownlint README.md -c ${GITHUB_WORKSPACE}/.github/markdown_lint.yaml -r ~MD029

  # YAML template from nf-core eager to trial
  yaml_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Install yaml-lint
        run: npm install -g yaml-lint

      - name: Run yaml-lint
        run: yamllint $(find ${GITHUB_WORKSPACE} -type f -name "*.yaml")
