name: Pipeline
#This is a workflow for minimal pipeline testing, triggered on a push or pull-request.
on:
  # Triggered on Push for any branch
  push:
    branches:
      - '*'
    # On change to workflow, pipeline
    paths:
      - '.github/workflows/pipeline.yaml'
      - 'pipeline.nf'

  # Triggered on PR for all branches, pipeline
  pull_request:
    branches:
      - '*'

jobs:

  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: phylo-env
          environment-file: phylo-env.yaml
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          conda list
          nextflow run pipeline.nf \
            --sqlite results/ncbimeta_db/update/latest/output/database/yersinia_pestis_db.sqlite \
            --max_datasets 4
