name: SRA
#This is a workflow for speciality pipeline feature, SRA Download and EAGER
on:
  # Triggered on Push for any branch
  push:
    branches:
      - '*'
    # On change to workflow, pipeline
    paths:
      - '.github/workflows/sra.yaml'
      - 'pipeline.nf'
      - 'phylo-env.yaml'

  # Triggered on PR for all branches, pipeline
  pull_request:
    branches:
      - '*'
  # Also on a published release
  release:
    types: [published]

jobs:

  pipeline:
    runs-on: ubuntu-latest
    steps:
      # 1. Check-out the plague-phylo repo
      - name: check-out repo
        uses: actions/checkout@v2

      # 2. Install nextflow
      - name: install nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      # 3. Setup the conda environment phylo-env
      - name: setup conda phylo-env
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: phylo-env
          environment-file: phylo-env.yaml
          auto-activate-base: false

      # 4. Pull the EAGER pipeline
      - name: pull eager
        shell: bash -l {0}
        run: |
          nextflow pull nf-core/eager -r dev
          conda env create -f ~/.nextflow/assets/nf-core/eager/environment.yml
          conda install -n nf-core-eager-2.2.0dev -c bioconda nextflow
          conda install -n nf-core-eager-2.2.0dev -c anaconda graphviz
          cp ~/.nextflow/assets/nf-core/eager/assets/multiqc_config.yaml \
             ./config/multiqc_config_eager.yaml;

      # Test the SRA EAGER Pipeline
      - name: sra download
        shell: bash -l {0}
        run: |
          nextflow run pipeline.nf \
            --sqlite results/ncbimeta_db/update/latest/output/database/yersinia_pestis_db.sqlite \
            --outdir test \
            --sqlite_select_command_sra "\"SELECT BioSampleAccession,SRARunAccession,SRALibraryLayout,SRAFileURL FROM Master WHERE (SRARunAccession = 'SRR1048902' OR SRARunAccession = 'SRR1048905')\"" \
            --max_datasets_sra 2  \
            --skip_assembly_download \
            --skip_eager \
            --skip_snippy_pairwise

      # EAGER test
      - name: eager test
        shell: bash -l {0}
        run: |
          nextflow run pipeline.nf \
            --sqlite results/ncbimeta_db/update/latest/output/database/yersinia_pestis_db.sqlite \
            --outdir test \
            --sqlite_select_command_sra "\"SELECT BioSampleAccession,SRARunAccession,SRALibraryLayout,SRAFileURL FROM Master WHERE (SRARunAccession = 'SRR1048902' OR SRARunAccession = 'SRR1048905')\"" \
            --max_datasets_sra 2  \
            --skip_assembly_download \
            --skip_snippy_pairwise \
            -resume

      # Artifact uploads
      - name: artifact SQLite import
        uses: actions/upload-artifact@v2
        with:
          name: sqlite-import
          path: test/sqlite_import/

      - name: artifact EAGER MultiQC
        uses: actions/upload-artifact@v2
        with:
          name: eager-multiqc
          path: test/eager/MultiQC

      - name: artifact trace
        uses: actions/upload-artifact@v2
        with:
          name: trace
          path: test/trace/
